version: "3"

services:

  webapp:
    image: javifmz/webapp-dnc
    volumes:
      - ./api:/webapp/api
      - ./web:/webapp/web
      - /webapp/api/vendor
      - /webapp/web/node_modules
    ports:
      - 8080:80
    environment:
      API_PATH: api
      API_PORT: 8081
      WEB_PORT: 8080
      COMMAND_START_NODE: yarn install && yarn serve
      COMMAND_START_COMPOSER: composer install && composer start
    
